name: Omochice
permalink: :year/:month/:day/:title
baseurl: /gh-pages

# Your blog's start year and this year, showed in the footer left
# start is optional
start: 2021
now: 2021

# Social links showed in the footer
# You just need modify the nickname of github and twitter
link:
  email: yourname@gmail.com
  github: Omochice
  twitter: omochicemgr
  bookmeter: 1179021

# Links in the navigation, you can modify both link name and link url
nav:
  Calendar: "/"
  Posts: "/posts"
  Profile: "/profile"
  Products: "/products"

markdown: kramdown
highlighter: rouge
kramdown:
  hard_wrap: true

sass:
  sass_dir: _sass
  style: compressed

exclude:
  - "Gemfile"
  - "Gemfile.lock"
  - "node_modules"
  - "vendor/bundle/"
  - "vendor/cache/"
  - "vendor/gems/"
  - "vendor/ruby/"
  - "templates/"
  - "README.md"

gems:
  - jekyll-seo-tag

twitter:
  username: omochicemgr
  card: summary

lang: ja_JP
