name: format markdown

on:
  push:


jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        id: extract_branch
      - uses: actions/setup-node@v2
      - name: install formatters
        run: |
          yarn add prettier textlint textlint-rule-preset-ja-spacing textlint-rule-ja-no-mixed-period textlint-rule-preset-ja-technical-writing textlint-rule-spellcheck-tech-word
      - name: formatting
        id: format
        run: |
          yarn run prettier --write _posts && yarn run textlint --fix _posts
      - name: Check for modified files
        id: git-check
        run: echo '::set-output name=modified::$(if git diff-index --quiet HEAD --; then echo "false"; else echo "true"; fi)'
      - name: Commit
        uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_messages: "[BOT] auto format by github actions"
          commit_user_name: "github-actions"
          commit_user_email: "github-actions[bot]@users.noreply.github.com"
      - name: Push
        if: ${{ steps.git-check.outputs.mofidied == 'true' }}
        run: git push origin

